parameters:
#    esprit_real_estate_agency.example.class: Esprit\RealEstateAgencyBundle\Example

services:
#    esprit_real_estate_agency.example:
#        class: %esprit_real_estate_agency.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
